### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by guihankenne** [noveni/laravel-docker#1]
Hi, 
I got a problem with running laravel, Composer say that the php version is too old. Laravel 5.5 require now PHP 7.1.3

`root@22abc12ac6ef:/var/www# composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=7.1.3 but your PHP version (7.0.1) does not satisfy that requirement.
  Problem 2
    - laravel/framework v5.6.0 requires php ^7.1.3 -> your PHP version (7.0.1) does not satisfy that requirement.
    - laravel/framework v5.6.0 requires php ^7.1.3 -> your PHP version (7.0.1) does not satisfy that requirement.
    - laravel/framework 5.6.x-dev requires php ^7.1.3 -> your PHP version (7.0.1) does not satisfy that requirement.
    - Installation request for laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev, v5.6.0].

`

**Comment by noveni** [comment]
Ok, I've updated the version of PHP to 7.2, and I've updated some package too.
