### ISSUE TITLE
./clipper build

### ISSUE THREAD

**Issue by guihankenne** [noveni/laravel-docker#3]
Hi,
I got a problem when I use the ./clipper build command. 
Here's the issue : 

`/usr/src/php/ext/ftp/php_ftp.c:29:26: fatal error: openssl/ssl.h: No such file or directory
 \# include <openssl/ssl.h>
                          ^
compilation terminated.
Makefile:193: recipe for target 'php_ftp.lo' failed
make: *** [php_ftp.lo] Error 1
ERROR: Service 'php' failed to build: The command '/bin/sh -c docker-php-ext-install ftp' returned a non-zero code: 2`

**Comment by noveni** [comment]
Problem due to the old version of PHP, Solved with #1
